image: nikolaik/python-nodejs

stages:
  - deploy-staging
  - production

before_script:
  - npm install -g firebase-tools
  
cache:
  paths:                
    - node_modules/     
  key: "$CI_BUILD_REPO" 

deploy:
  stage: production
  only:
    - master
  script:
    - export NODE_ENV=production REACT_APP_RAVE_ENDPOINT=$RAVE_ENDPOINT REACT_APP_GRAPHQL_API=$GRAPHQL_API NODE_PATH=src REACT_APP_RAVE_PUBLIC_KEY=$REACT_APP_RAVE_PUBLIC_KEY REACT_APP_RAVE_SECRET_KEY=$REACT_APP_RAVE_SECRET_KEY REACT_APP_RAVE_ENCRYPT_KEY=$REACT_APP_RAVE_ENCRYPT_KEY CI="" REACT_APP_SEGMENT_KEY=$SEGMENT_WRITE_KEY REACT_APP_SEGMENT_APP=$SEGMENT_APP_NAME # set REACT_APP variables before build command
    - npm install
    - npm run build
    - firebase use spincrowapp --token $FIREBASE_CI_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_CI_TOKEN

deploy-staging:
  stage: deploy-staging
  only:
    - dev
  script:
    - export NODE_ENV=development REACT_APP_RAVE_ENDPOINT=$RAVE_TEST_ENDPOINT REACT_APP_GRAPHQL_API=$GRAPHQL_TEST_API NODE_PATH=src REACT_APP_RAVE_PUBLIC_KEY=$REACT_APP_RAVE_PUBLIC_TEST_KEY REACT_APP_RAVE_SECRET_KEY=$REACT_APP_RAVE_SECRET_TEST_KEY REACT_APP_RAVE_ENCRYPT_KEY=$REACT_APP_RAVE_ENCRYPT_TEST_KEY CI="" REACT_APP_SEGMENT_KEY=$SEGMENT_WRITE_KEY_DEV REACT_APP_SEGMENT_APP=$SEGMENT_APP_NAME_DEV # set REACT_APP variables before build command
    - npm install
    - npm run build
    - firebase use spincrow-dev --token $FIREBASE_CI_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_CI_TOKEN
# production:
#    type: deploy
#    stage: production
#    image: ruby:latest
#    script:
#        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
#    only:
#        - master
